### ISSUE TITLE
Possible to decrypt/encrypt entire images?

### ISSUE THREAD

**Issue by Sierraffinity** [koolkdev/wfslib#17]
Hi,
I'm trying to figure out a way to decrypt a donor MLC from one Wii U and encrypt it with the keys from another Wii U, to essentially make a "clone" of it. I'm trying to puzzle out how to do this with wfslib, or at least gain an idea of how the encryption scheme works so I can do it myself in another program, but the code is too dense for me to understand...

So, is there a way to decrypt the data block by block, copy it to another image, then encrypt it with a new key? Or does it have to be done file by file?

**Comment by piratesephiroth** [comment]
I don't think the filesystem has been entirely figured out yet so full decryption/encryption can be performed.
Probably the best that can be done is individual file replacement.

**Comment by Sierraffinity** [comment]
So the encryption is done on a per file basis? Because I had imagined it being per-block, and that you would just poke into each block to pull out the file data. Is there any documentation for this format besides wfslib's code?

**Comment by koolkdev** [comment]
The encryption is done per block basis. And it is based on context (block size, offset from area start, etc..).
So in order such feature 100% of the file system have to be figured out that you could traverse all the blocks.
I am in the way to there, but it is going to take time....

**Comment by Sierraffinity** [comment]
Gotcha. With the current knowledge of the filesystem, do you know of a way to fix the size of a file? The first thing I tried when repairing the original image was grabbing some working files from a different dump and overwriting the ones that seemed to be broken but because the filesize was different, the tool wouldn't let me overwrite it.

**Comment by talkeren** [comment]
The tool can't increase the size that is allocated to the file because it will require allocating new blocks.

The research is done and now I am working on implementing modification abilities for the file system. It will take some time.
actually I think that it will be simpler to implement the tool that reencrypt the file system first

**Comment by koolkdev** [comment]
The tool can't increase the size that is allocated to the file because it will require allocating new blocks.

The research is done and now I am working on implementing modification abilities for the file system. It will take some time.
actually I think that it will be simpler to implement the tool that reencrypt the file system first

**Comment by koolkdev** [comment]
Just an update - added the promised wfs-reencryptor tool. It is not in the release as it is still experimental but it can be built from source or be downloaded from a build artifact.
